export const FETCH_MESSAGES = 'FETCH_MESSAGES';
export const FETCH_ALL_MESSAGES = 'FETCH_ALL_MESSAGES';
export const TRASH_MESSAGE = 'TRASH_MESSAGE';

export const FETCH_ORGANIZER_MESSAGES = 'FETCH_ORGANIZER_MESSAGES';
export const FETCH_ORGANIZER_ALL_MESSAGES = 'FETCH_ORGANIZER_ALL_MESSAGES';